service: url-shortener-nestjs

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - db:*
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
resources:
  Resources:
    UrlLinkTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LinkTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    UrlStatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StatsTable
        AttributeDefinitions:
          - AttributeName: linkId
            AttributeType: S
          - AttributeName: platformCreatedAtId
            AttributeType: S
        KeySchema:
          - AttributeName: linkId
            KeyType: HASH
          - AttributeName: platformCreatedAtId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
custom:
  serverless-offline:
    httpPort: 3000
